"""add_docs_hash_to_integration

Revision ID: 318e319eff36
Revises: f2bfcc698dfa
Create Date: 2026-05-09 00:24:12.906107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '318e319eff36'
down_revision: Union[str, None] = 'f2bfcc698dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('docs_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integrations', 'docs_hash')
    # ### end Alembic commands ###
