"""add health_check_url to integrations

Revision ID: 5b0df36aa9b3
Revises: ab943d9e8cfd
Create Date: 2026-04-29 20:01:28.588297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b0df36aa9b3'
down_revision: Union[str, None] = 'ab943d9e8cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('health_check_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integrations', 'health_check_url')
    # ### end Alembic commands ###
