"""add timestamp columns to users

Revision ID: 6ad4d8bb27a8
Revises: 2153695ba95e
Create Date: 2026-04-09 01:27:44.648519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad4d8bb27a8'
down_revision: Union[str, None] = '2153695ba95e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
